modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory A version range to match for said mod loader - for regular FML @Mod it will be the forge version
license="All rights reserved"
issueTrackerURL="https://github.com/BarionLP/DungeonsEnhanced/issues" #optional

[[mods]] #mandatory A list of mods - how many allowed here is determined by the individual mod loader
    modId="dungeons_enhanced" #mandatory
    version="3.2" #mandatory
    displayName="Dungeons Enhanced" #mandatory
    #updateJSONURL="https://change.me.example.invalid/updates.json" #optional See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
    displayURL="https://www.curseforge.com/minecraft/mc-mods/dungeonsenhanced" #optional A URL for the "homepage" for this mod
    logoFile="logo.png"
    credits="Thanks Modding Legacy for their genius Structure Gel API" #optional
    authors="Barion, Valarauko9" #optional
    # The description text for the mod (multi line!) (#mandatory)
    description='''
Minecraft is great game, but exploring always felt a bit boring for us. There aren't many structures or dungeons you can explore and the ones you find, are getting repetitive. We decided to spice things up a bit, by adding new dungeons and structures for you to explore. By now 20 new dungeons and structures are include in our mod. They all fit a medival/fantasy theme and could fit along other fantasy or RPG-like Mods. Some of our structures also look like they could be a upgraded version of a vanilla structure or a variant to them. Get ready to find huge mazes under trees, castles, towers and forgotten temples.

We hope you have fun.
'''

[[dependencies.dungeons_enhanced]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory   Does this dependency have to exist - if not, ordering below must be specified
    versionRange="[40,)" #mandatory
    ordering="NONE" # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    side="BOTH" #BOTH, CLIENT or SERVER
[[dependencies.dungeons_enhanced]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)" # declares a minimum of the current minecraft version up to but not including the next major version
    ordering="NONE"
    side="BOTH"
[[dependencies.dungeons_enhanced]]
    modId="structure_gel"
    mandatory=true
    versionRange="[2.3,]"
    ordering="NONE"
    side="BOTH"