modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"
issueTrackerURL="https://github.com/BarionLP/DungeonsEnhanced/issues"

[[mods]] #mandatory
    modId="${mod_id}" #mandatory
    version="${mod_version}" #mandatory
    displayName="${mod_name}" #mandatory
    #updateJSONURL="https://change.me.example.invalid/updates.json" # See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
    displayURL="https://www.curseforge.com/minecraft/mc-mods/dungeonsenhanced"
    logoFile="logo.png"
    credits="Thanks Modding Legacy for their genius Structure Gel API"
    authors="${mod_authors}"
    displayTest="MATCH_VERSION"
    description='''
        Minecraft is great game, but exploring always felt a bit boring for us.
        There aren't many structures or dungeons you can explore and the ones you find, are getting repetitive.
        We decided to spice things up a bit, by adding new dungeons and structures for you to explore.
        By now 26 new dungeons and structures are included in our mod.
        They all fit a medieval/fantasy theme and could fit along other fantasy or RPG-like Mods.
        Some of our structures also look like they could be an upgraded version of a vanilla structure or a variant to them.
        Get ready to find huge mazes under trees, castles, towers and forgotten temples.
        We hope you have fun!
    '''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="structure_gel"
    type="required"
    versionRange="${gel_version_range}"
    ordering="NONE"
    side="BOTH"

[[accessTransformers]]
    file="dungeons_enhanced_base.cfg"