modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"
issueTrackerURL="https://github.com/BarionLP/DungeonsEnhanced/issues" #optional

[[mods]] #mandatory A list of mods - how many allowed here is determined by the individual mod loader
    modId="${mod_id}" #mandatory
    version="${mod_version}" #mandatory
    displayName="${mod_name}" #mandatory
    #updateJSONURL="https://change.me.example.invalid/updates.json" #optional See the JSON update specification https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
    displayURL="https://www.curseforge.com/minecraft/mc-mods/dungeonsenhanced" #optional A URL for the "homepage" for this mod
    logoFile="logo.png"
    credits="Thanks to Modding Legacy for their genius Structure Gel API" #optional
    authors="${mod_authors}" #optional
    # The description text for the mod (multi line!) (#mandatory)
    description='''
Minecraft is great game, but exploring always felt a bit boring for us. There aren't many structures or dungeons you can explore and the ones you find, are getting repetitive. We decided to spice things up a bit, by adding new dungeons and structures for you to explore. By now 25 new dungeons and structures are include in our mod. They all fit a medival/fantasy theme and could fit along other fantasy or RPG-like Mods. Some of our structures also look like they could be a upgraded version of a vanilla structure or a variant to them. Get ready to find huge mazes under trees, castles, towers and forgotten temples.

We hope you have fun.
'''

[[dependencies.${mod_id}]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="structure_gel"
    mandatory=true
    versionRange="${gel_version_range}"
    ordering="NONE"
    side="BOTH"