
[building_tool]
	#
	# The amount of undo operations saved by the Building Tool.
	# Default: 32
	#Range: 8 ~ 256
	max_undos = 32

[debug]
	#
	# When true, allows extra debug logging to be printed to the console.
	# Default: false
	console_debug = false
	#
	# When true:
	# - Gel blocks can be clicked through like air when holding items that don't interact with them.
	# - Gel blocks can be replaced like air when not holding gel or crouching.
	# - Gel blocks automatically replace destroyed neighboring blocks.
	# Default: true
	advanced_gel_behavior = true

