license="${mod_license}"
issueTrackerURL="https://github.com/Ametrin-Studios/DungeonsEnhanced/issues"

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
updateJSONURL="https://raw.githubusercontent.com/Ametrin-Studios/DungeonsEnhanced/refs/heads/main/update.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/dungeonsenhanced"
logoFile="banner.png"
# credits=""
authors="${mod_authors}"
displayTest="MATCH_VERSION"
description='''
        - Explore a world worth exploring. -

        Minecraft is a great game, but we felt exploration was missing something.
        There are only a handful of dungeons and they are getting repetitive.
        So we decided to spice things up a bit, by adding new dungeons and structures for you to explore.
        This mod adds 27 new dungeons and structures, all designed with a medieval fantasy theme.
        Some look like upgraded or alternative versions of vanilla structures, while others are completely new.
        They fit naturally into any world and work well alongside other fantasy and RPG mods.
        Get ready to find huge mazes hidden beneath trees, castles, towers and forgotten temples.
        Grab your sword, pack some food and start exploring. We hope you have fun!
    '''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="ametrin"
    type="required"
    versionRange="${ametrin_version_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="ametrin_structures"
    type="required"
    versionRange="${ametrin_structures_version_range}"
    ordering="AFTER"
    side="BOTH"
